### PR TITLE
Backend: extend question module with features like answers/follow-up comments, upvotes, etc.

### PR DESCRIPTION
**Pull request by plotkin1996**
- [x] Support for follow-up posts
- [ ] Flag system (accept/answered statuses)
- [x] Upvoting/supporting
- [x] Store date/time
- [ ] Allow dynamic fetch (so that old questions are not fetched unless requested)
- [ ] Moderation
- [x] Rework tests (these are mess right now, my bad)

### CODE REVIEW

**Comment by Astroxslurg** [comment]
Tried it, but nothing happened when I tried to post a question :/
Nor did I understand what was needed to be done.

**Comment by plotkin1996** [comment]
>>>Astroxslurg
It is only in backend (and API is different now, so this breaks everything until we've got a new frontend).

**Comment by Astroxslurg** [comment]
I see, where is the API documented?

**Comment by plotkin1996** [comment]
devdocs/API

**Pull request merged**
